// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzd38x3CF2f2ccntI6iHLjSGoq4IyqRE',
    appId: '1:128720778231:web:59c324092177f445ebf4f2',
    messagingSenderId: '128720778231',
    projectId: 'attendence-a56dd',
    authDomain: 'attendence-a56dd.firebaseapp.com',
    storageBucket: 'attendence-a56dd.firebasestorage.app',
    measurementId: 'G-YW8QXYSK2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSlGK6y2ztaTfLm8tPpNa5wYoWkSxLzJY',
    appId: '1:128720778231:android:3f04d1930c29df68ebf4f2',
    messagingSenderId: '128720778231',
    projectId: 'attendence-a56dd',
    storageBucket: 'attendence-a56dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4SbMiipe1J5Zf3r5A1rgVHC-6hqg7-M',
    appId: '1:128720778231:ios:77f19b389ff49657ebf4f2',
    messagingSenderId: '128720778231',
    projectId: 'attendence-a56dd',
    storageBucket: 'attendence-a56dd.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4SbMiipe1J5Zf3r5A1rgVHC-6hqg7-M',
    appId: '1:128720778231:ios:77f19b389ff49657ebf4f2',
    messagingSenderId: '128720778231',
    projectId: 'attendence-a56dd',
    storageBucket: 'attendence-a56dd.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnzd38x3CF2f2ccntI6iHLjSGoq4IyqRE',
    appId: '1:128720778231:web:fa4644d9fca7003eebf4f2',
    messagingSenderId: '128720778231',
    projectId: 'attendence-a56dd',
    authDomain: 'attendence-a56dd.firebaseapp.com',
    storageBucket: 'attendence-a56dd.firebasestorage.app',
    measurementId: 'G-N1C6VRKK0J',
  );
}
